# BEGIN_KITTY_THEME
#include afterglow.conf
include ayu_mirage.conf
#include chalk.conf
#include gruvbox_dark.conf
#include seafoam_pastel.conf 

# GENERAL
font_family Jetbrains-mono
font_size 12

# STYLES

window_padding_width 7
window_padding_height 10

scrollback_lines 3000

map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

background_opacity 0.8
enable_background_blur yes
background_blur 1

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge top
tab_bar_align left
active_tab_font_style bold
inactive_tab_font_style normal

# KEYBINDS
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab


# END_KITTY_THEME
